### ISSUE TITLE
Performance by OpenMPI vs MPICH

### ISSUE THREAD

**Issue by HanL2021** [LLNL/Aluminum#204]
Will they be different?

**Comment by ndryden** [comment]
Aluminum should not introduce meaningful overhead to MPI (unless what you are doing is _very_ latency-sensitive), so any performance difference between the two will be entirely due to the MPI library and how it is configured and tuned for your system.

I think that exploring such differences is out-of-scope for discussion on Aluminum, since that is very system dependent. You will likely have more luck contacting your cluster admins.
